# ============================================
# PRODUCTION docker-compose configuration file
# ============================================

version: "3.1"

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Dizify
    networks:
      - dizify
    restart: always
    ports:
      - 3306:3306

  api:
    image: leopoldbriand/dizify:api-1.0.4
    container_name: api
    ports:
      - 8080:8080
    links:
      - mariadb
    networks:
      - dizify
    restart: always

  front:
    image: leopoldbriand/dizify:front-1.0.1
    container_name: front
    ports:
      - 3000:3000
    links:
      - api
    networks:
      - dizify
    restart: always

networks:
  dizify:
    driver: "bridge"
    